import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import Placeholder from "@tiptap/extension-placeholder";
import { Markdown } from "tiptap-markdown";
import { useEffect, useRef } from "react";
import { cn } from "@renderer/lib/utils";

export function CommitDescriptionEditor({
  value,
  onChange,
  className,
}: {
  value: string;
  onChange: (value: string) => void;
  className?: string;
}) {
  // Use a ref to prevent update cycles loop during active editing
  const lastEmittedValue = useRef(value);

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        heading: { levels: [1, 2, 3, 4] },
      }),
      Placeholder.configure({
        placeholder: "Description (Supports Markdown)...",
        emptyEditorClass:
          "is-editor-empty before:content-[attr(data-placeholder)] before:text-muted-foreground/70 before:float-left before:pointer-events-none before:h-0",
      }),
      Markdown.configure({
        html: false,
        breaks: true,
      }),
    ],
    content: value,
    editorProps: {
      attributes: {
        class: cn(
          "w-full max-w-none focus:outline-none min-h-0",
          "[&_p]:my-1 [&_h1]:text-[16px] [&_h1]:font-semibold [&_h1]:my-2 [&_h2]:text-[14px] [&_h2]:font-semibold [&_h2]:my-2 [&_h3]:text-[13px] [&_h3]:font-semibold [&_h3]:my-1.5 [&_h4]:text-[12px] [&_h4]:font-semibold [&_h4]:my-1",
          "[&_ul]:my-1 [&_ul]:list-disc [&_ul]:pl-4 [&_ol]:my-1 [&_ol]:list-decimal [&_ol]:pl-4 [&_li]:my-0.5",
          "[&_code]:bg-secondary/50 [&_code]:px-1 [&_code]:py-0.5 [&_code]:rounded [&_pre]:bg-secondary/30 [&_pre]:p-2 [&_pre]:rounded [&_a]:text-blue-400 [&_a]:underline",
          "[&_blockquote]:border-l-2 [&_blockquote]:border-muted-foreground/30 [&_blockquote]:pl-3 [&_blockquote]:my-2 [&_blockquote]:text-muted-foreground [&_blockquote]:italic",
          "[&_strong]:font-semibold [&_em]:italic"
        ),
      },
    },
    onUpdate: ({ editor }) => {
      // @ts-ignore - Tiptap doesn't strongly type its storage out of the box for extensions
      const markdown = editor.storage.markdown.getMarkdown();
      lastEmittedValue.current = markdown;
      onChange(markdown);
    },
  });

  useEffect(() => {
    // Only update the editor if the new value didn't originate from this component
    // (e.g. cleared externally or generated by AI)
    if (editor && value !== lastEmittedValue.current) {
      // @ts-ignore
      const currentMarkdown = editor.storage.markdown.getMarkdown();
      if (value !== currentMarkdown) {
        editor.commands.setContent(value);
        lastEmittedValue.current = value;
      }
    }
  }, [value, editor]);

  return (
    <EditorContent
      editor={editor}
      className={cn("flex-1 overflow-y-auto cursor-text text-[12px] p-2 leading-relaxed text-foreground", className)}
      onClick={() => editor?.commands.focus()}
    />
  );
}
