import type { Config } from "tailwindcss";

export default {
  content: ["./src/renderer/index.html", "./src/renderer/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        shell: {
          950: "#f6f8fc",
          900: "#eef3f9",
          850: "#e6edf6",
          800: "#dce5f0",
          760: "#d2ddea",
          700: "#bccbdd",
          600: "#97a8bb",
          500: "#6f8096",
          400: "#526171",
          300: "#3a4654",
          200: "#25313d",
          100: "#121b24",
        },
        accent: {
          500: "#2f76d2",
          400: "#4b8de0",
          300: "#6fa7f0",
        },
        lime: {
          400: "#4ca66a",
        },
        // Semantic tokens — resolve to CSS variables from theme.css
        "bg-primary":    "var(--color-bg-primary)",
        "bg-secondary":  "var(--color-bg-secondary)",
        "bg-tertiary":   "var(--color-bg-tertiary)",
        "text-primary":  "var(--color-text-primary)",
        "text-secondary":"var(--color-text-secondary)",
        "text-muted":    "var(--color-text-muted)",
        "step-card":     "var(--color-step-bg)",
        "step-hover":    "var(--color-step-bg-hover)",
        "step-border":   "var(--color-step-border)",
        "status-exec":   "var(--color-status-executing)",
        "status-ok":     "var(--color-status-success)",
        "status-err":    "var(--color-status-error)",
        "status-think":  "var(--color-status-thinking)",
        "status-cancel": "var(--color-status-cancelled)",
        "code-bg":       "var(--color-code-bg)",
        "code-text":     "var(--color-code-text)",
        "diff-add-bg":   "var(--color-diff-add-bg)",
        "diff-add-text": "var(--color-diff-add-text)",
        "diff-del-bg":   "var(--color-diff-del-bg)",
        "diff-del-text": "var(--color-diff-del-text)",
        "pi-accent":     "var(--color-accent)",
        "pi-accent-hover":"var(--color-accent-hover)",
        "pi-accent-subtle":"var(--color-accent-subtle)",
        "shell-window":  "var(--color-shell-window)",
        "shell-panel":   "var(--color-shell-panel)",
        "shell-panel-muted":"var(--color-shell-panel-muted)",
        "shell-panel-elevated":"var(--color-shell-panel-elevated)",
        "shell-panel-contrast":"var(--color-shell-panel-contrast)",
        "shell-border":  "var(--color-shell-border)",
        "shell-toolbar": "var(--color-shell-toolbar)",
        "shell-toolbar-hover":"var(--color-shell-toolbar-hover)",
        "shell-hover":   "var(--color-shell-hover)",
        "shell-terminal":"var(--color-shell-terminal)",
        "shell-resize":  "var(--color-shell-resize-handle)",
        "shell-resize-hover":"var(--color-shell-resize-handle-hover)",
      },
      fontFamily: {
        sans: ['"Segoe UI Variable"', '"PingFang SC"', '"Microsoft YaHei UI"', "sans-serif"],
      },
      boxShadow: {
        glow: "0 16px 36px rgba(84, 102, 132, 0.14)",
      },
      keyframes: {
        "panel-in": {
          "0%": { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "panel-in": "panel-in 220ms ease-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
