import type { Config } from "tailwindcss";

export default {
  content: ["./src/renderer/index.html", "./src/renderer/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        chela: {
          50: "var(--chela-gray-50)",
          100: "var(--chela-gray-100)",
          200: "var(--chela-gray-200)",
          300: "var(--chela-gray-300)",
          400: "var(--chela-gray-400)",
          500: "var(--chela-gray-500)",
          600: "var(--chela-gray-600)",
          700: "var(--chela-gray-700)",
          800: "var(--chela-gray-800)",
          900: "var(--chela-gray-900)",
          950: "var(--chela-gray-950)",
        },
        // Semantic tokens — resolve to CSS variables from theme.css
        "bg-primary": "var(--color-bg-primary)",
        "bg-secondary": "var(--color-bg-secondary)",
        "bg-tertiary": "var(--color-bg-tertiary)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "step-card": "var(--color-step-bg)",
        "step-hover": "var(--color-step-bg-hover)",
        "step-border": "var(--color-step-border)",
        "status-exec": "var(--color-status-executing)",
        "status-ok": "var(--color-status-success)",
        "status-err": "var(--color-status-error)",
        "status-think": "var(--color-status-thinking)",
        "status-cancel": "var(--color-status-cancelled)",
        "code-bg": "var(--color-code-bg)",
        "code-text": "var(--color-code-text)",
        "diff-add-bg": "var(--color-diff-add-bg)",
        "diff-add-text": "var(--color-diff-add-text)",
        "diff-del-bg": "var(--color-diff-del-bg)",
        "diff-del-text": "var(--color-diff-del-text)",
        "pi-accent": "var(--color-accent)",
        "pi-accent-hover":"var(--color-accent-hover)",
        "pi-accent-subtle":"var(--color-accent-subtle)",
        "shell-window":  "var(--color-shell-window)",
        "shell-panel":   "var(--color-shell-panel)",
        "shell-panel-muted":"var(--color-shell-panel-muted)",
        "shell-panel-elevated":"var(--color-shell-panel-elevated)",
        "shell-panel-contrast":"var(--color-shell-panel-contrast)",
        "shell-overlay":"var(--color-shell-overlay)",
        "shell-border":  "var(--color-shell-border)",
        "shell-toolbar": "var(--color-shell-toolbar)",
        "shell-toolbar-hover":"var(--color-shell-toolbar-hover)",
        "shell-hover":   "var(--color-shell-hover)",
        "shell-terminal":"var(--color-shell-terminal)",
        "shell-resize":  "var(--color-shell-resize-handle)",
        "shell-resize-hover":"var(--color-shell-resize-handle-hover)",
        "selection-bg": "var(--color-selection-bg)",
        "selection-fg": "var(--color-selection-fg)",
        "selection-muted-bg": "var(--color-selection-muted-bg)",
        "focus-ring": "var(--color-focus-ring)",
        // New Pure Ink semantic tokens
        "iconbar": "var(--chela-bg-iconbar)",
        "sessionlist": "var(--chela-bg-sessionlist)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
        shell: "var(--radius-shell)",
      },
      fontFamily: {
        sans: [
          "Inter",
          '"Segoe UI Variable"',
          '"PingFang SC"',
          '"Microsoft YaHei UI"',
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          '"Fira Code"',
          "Consolas",
          "monospace",
        ],
      },
      boxShadow: {
        glow: "0 16px 36px rgba(84, 102, 132, 0.14)",
        subtle: "var(--shadow-subtle)",
        flyout: "var(--shadow-flyout)",
        "inset-soft": "var(--shadow-inset-soft)",
      },
      transitionDuration: {
        fast: "var(--motion-duration-fast)",
        base: "var(--motion-duration-base)",
        slow: "var(--motion-duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-ease-standard)",
        emphasized: "var(--motion-ease-emphasized)",
      },
      keyframes: {
        "panel-in": {
          "0%": { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "panel-in": "panel-in 220ms ease-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
