import type {
  DesktopApi,
  ModelEntry,
  ProviderSource,
  ProviderType,
} from "@shared/contracts";

export type SelectableModelOption = {
  value: string;
  label: string;
  description: string;
  groupId: string;
  groupLabel: string;
  sourceId: string;
  entry: ModelEntry;
  source: ProviderSource;
};

type ProviderDirectorySnapshot = {
  sources: ProviderSource[];
  entries: ModelEntry[];
};

type LoadProviderDirectoryOptions = {
  force?: boolean;
  signal?: AbortSignal;
  timeoutMs?: number;
};

let providerDirectoryCache:
  | ProviderDirectorySnapshot
  | null = null;
let providerDirectoryPromise:
  | Promise<ProviderDirectorySnapshot>
  | null = null;
const PROVIDER_DIRECTORY_UPDATED_EVENT = "chela:provider-directory-updated";
const PROVIDER_DIRECTORY_REQUEST_TIMEOUT_MS = 5_000;

function createAbortError(message: string): Error {
  const error = new Error(message);
  error.name = "AbortError";
  return error;
}

function withAbortAndTimeout<T>(
  factory: () => Promise<T>,
  options: { signal?: AbortSignal; timeoutMs: number },
): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const { signal, timeoutMs } = options;

    if (signal?.aborted) {
      reject(createAbortError("已取消加载模型目录。"));
      return;
    }

    const timer = globalThis.setTimeout(() => {
      cleanup();
      reject(new Error(`加载模型目录超时（>${timeoutMs}ms）。`));
    }, timeoutMs);

    const handleAbort = () => {
      cleanup();
      reject(createAbortError("已取消加载模型目录。"));
    };

    const cleanup = () => {
      globalThis.clearTimeout(timer);
      signal?.removeEventListener("abort", handleAbort);
    };

    signal?.addEventListener("abort", handleAbort, { once: true });

    factory()
      .then((value) => {
        cleanup();
        resolve(value);
      })
      .catch((error) => {
        cleanup();
        reject(error);
      });
  });
}

function canReuseSharedProviderDirectoryPromise(
  options?: LoadProviderDirectoryOptions,
): boolean {
  return (
    !options?.force &&
    !options?.signal &&
    (options?.timeoutMs === undefined ||
      options.timeoutMs === PROVIDER_DIRECTORY_REQUEST_TIMEOUT_MS)
  );
}

function fetchProviderDirectory(
  desktopApi: DesktopApi,
  options?: LoadProviderDirectoryOptions,
): Promise<ProviderDirectorySnapshot> {
  return withAbortAndTimeout(
    () =>
      Promise.all([
        desktopApi.providers.listSources(),
        desktopApi.models.listEntries(),
      ]).then(([sources, entries]) => {
        providerDirectoryCache = { sources, entries };
        return providerDirectoryCache;
      }),
    {
      signal: options?.signal,
      timeoutMs:
        options?.timeoutMs ?? PROVIDER_DIRECTORY_REQUEST_TIMEOUT_MS,
    },
  );
}

function deriveLegacyModelEntryName(modelId: string): string {
  return modelId
    .replace(/\//g, " / ")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function deriveModelEntryName(modelId: string): string {
  const trimmed = modelId.trim();
  if (!trimmed) {
    return "未命名模型";
  }

  return trimmed;
}

export function isAutoGeneratedModelEntryName(
  name: string,
  modelId: string,
): boolean {
  const trimmedName = name.trim();
  const trimmedModelId = modelId.trim();

  if (!trimmedName) {
    return true;
  }

  if (!trimmedModelId) {
    return false;
  }

  return (
    trimmedName === trimmedModelId ||
    trimmedName === deriveLegacyModelEntryName(trimmedModelId)
  );
}

export function resolveModelEntryName(
  entry: Pick<ModelEntry, "name" | "modelId" | "builtin">,
): string {
  if (entry.builtin) {
    return entry.name;
  }

  return isAutoGeneratedModelEntryName(entry.name, entry.modelId)
    ? deriveModelEntryName(entry.modelId)
    : entry.name.trim();
}

export async function loadProviderDirectory(
  desktopApi: DesktopApi,
  options?: LoadProviderDirectoryOptions,
) {
  if (!options?.force && providerDirectoryCache) {
    return providerDirectoryCache;
  }

  const canReuseSharedPromise = canReuseSharedProviderDirectoryPromise(options);

  if (canReuseSharedPromise && providerDirectoryPromise) {
    return providerDirectoryPromise;
  }

  const request = fetchProviderDirectory(desktopApi, options);

  if (!canReuseSharedPromise) {
    return request;
  }

  providerDirectoryPromise = request.finally(() => {
    providerDirectoryPromise = null;
  });

  return providerDirectoryPromise;
}

export function invalidateProviderDirectoryCache(): void {
  providerDirectoryCache = null;
  providerDirectoryPromise = null;
}

export function notifyProviderDirectoryChanged(): void {
  invalidateProviderDirectoryCache();

  if (typeof window === "undefined") {
    return;
  }

  window.dispatchEvent(new Event(PROVIDER_DIRECTORY_UPDATED_EVENT));
}

export function subscribeProviderDirectoryChanged(
  listener: () => void,
): () => void {
  if (typeof window === "undefined") {
    return () => undefined;
  }

  const handler = () => listener();
  window.addEventListener(PROVIDER_DIRECTORY_UPDATED_EVENT, handler);
  return () => {
    window.removeEventListener(PROVIDER_DIRECTORY_UPDATED_EVENT, handler);
  };
}

export function buildSelectableModelOptions(
  sources: ProviderSource[],
  entries: ModelEntry[],
): SelectableModelOption[] {
  const sourceMap = new Map(sources.map((source) => [source.id, source]));

  return entries
    .map((entry) => {
      const source = sourceMap.get(entry.sourceId);
      if (!source || !source.enabled || !entry.enabled) {
        return null;
      }

      return {
        value: entry.id,
        label: resolveModelEntryName(entry),
        description: source.name,
        groupId: source.id,
        groupLabel: source.name,
        sourceId: source.id,
        entry,
        source,
      } satisfies SelectableModelOption;
    })
    .filter((option): option is SelectableModelOption => !!option)
    .sort((left, right) => {
      const groupCompare = left.groupLabel.localeCompare(right.groupLabel, "zh-CN");
      if (groupCompare !== 0) {
        return groupCompare;
      }

      return left.label.localeCompare(right.label, "zh-CN");
    });
}

export function findEntryLabel(
  entryId: string,
  sources: ProviderSource[],
  entries: ModelEntry[],
): string {
  const sourceMap = new Map(sources.map((source) => [source.id, source]));
  const entry = entries.find((item) => item.id === entryId);
  const source = entry ? sourceMap.get(entry.sourceId) : undefined;

  if (!entry) {
    return "当前模型";
  }

  const entryLabel = resolveModelEntryName(entry);
  return source ? `${entryLabel} · ${source.name}` : entryLabel;
}

export function providerTypeLabel(providerType: ProviderType): string {
  switch (providerType) {
    case "anthropic":
      return "Anthropic";
    case "openai":
      return "OpenAI";
    case "google":
      return "Google";
    case "openai-compatible":
      return "OpenAI Compatible";
  }
}

export function sourceModeLabel(source: ProviderSource): string {
  if (source.kind === "custom") {
    return "自定义接入";
  }

  return source.mode === "native" ? "官方接口" : "自定义中转";
}
