import type {
  DesktopApi,
  ModelEntry,
  ProviderSource,
  ProviderType,
} from "@shared/contracts";

export type SelectableModelOption = {
  value: string;
  label: string;
  description: string;
  groupId: string;
  groupLabel: string;
  sourceId: string;
  entry: ModelEntry;
  source: ProviderSource;
};

let providerDirectoryCache:
  | { sources: ProviderSource[]; entries: ModelEntry[] }
  | null = null;
let providerDirectoryPromise:
  | Promise<{ sources: ProviderSource[]; entries: ModelEntry[] }>
  | null = null;

function deriveLegacyModelEntryName(modelId: string): string {
  return modelId
    .replace(/\//g, " / ")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function deriveModelEntryName(modelId: string): string {
  const trimmed = modelId.trim();
  if (!trimmed) {
    return "未命名模型";
  }

  return trimmed;
}

export function isAutoGeneratedModelEntryName(
  name: string,
  modelId: string,
): boolean {
  const trimmedName = name.trim();
  const trimmedModelId = modelId.trim();

  if (!trimmedName) {
    return true;
  }

  if (!trimmedModelId) {
    return false;
  }

  return (
    trimmedName === trimmedModelId ||
    trimmedName === deriveLegacyModelEntryName(trimmedModelId)
  );
}

export function resolveModelEntryName(
  entry: Pick<ModelEntry, "name" | "modelId" | "builtin">,
): string {
  if (entry.builtin) {
    return entry.name;
  }

  return isAutoGeneratedModelEntryName(entry.name, entry.modelId)
    ? deriveModelEntryName(entry.modelId)
    : entry.name.trim();
}

export async function loadProviderDirectory(
  desktopApi: DesktopApi,
  options?: { force?: boolean },
) {
  if (!options?.force && providerDirectoryCache) {
    return providerDirectoryCache;
  }

  if (!options?.force && providerDirectoryPromise) {
    return providerDirectoryPromise;
  }

  providerDirectoryPromise = Promise.all([
    desktopApi.providers.listSources(),
    desktopApi.models.listEntries(),
  ]).then(([sources, entries]) => {
    providerDirectoryCache = { sources, entries };
    providerDirectoryPromise = null;
    return providerDirectoryCache;
  });

  return providerDirectoryPromise;
}

export function buildSelectableModelOptions(
  sources: ProviderSource[],
  entries: ModelEntry[],
): SelectableModelOption[] {
  const sourceMap = new Map(sources.map((source) => [source.id, source]));

  return entries
    .map((entry) => {
      const source = sourceMap.get(entry.sourceId);
      if (!source || !source.enabled || !entry.enabled) {
        return null;
      }

      return {
        value: entry.id,
        label: resolveModelEntryName(entry),
        description: source.name,
        groupId: source.id,
        groupLabel: source.name,
        sourceId: source.id,
        entry,
        source,
      } satisfies SelectableModelOption;
    })
    .filter((option): option is SelectableModelOption => !!option)
    .sort((left, right) => {
      const groupCompare = left.groupLabel.localeCompare(right.groupLabel, "zh-CN");
      if (groupCompare !== 0) {
        return groupCompare;
      }

      return left.label.localeCompare(right.label, "zh-CN");
    });
}

export function findEntryLabel(
  entryId: string,
  sources: ProviderSource[],
  entries: ModelEntry[],
): string {
  const sourceMap = new Map(sources.map((source) => [source.id, source]));
  const entry = entries.find((item) => item.id === entryId);
  const source = entry ? sourceMap.get(entry.sourceId) : undefined;

  if (!entry) {
    return "当前模型";
  }

  const entryLabel = resolveModelEntryName(entry);
  return source ? `${entryLabel} · ${source.name}` : entryLabel;
}

export function providerTypeLabel(providerType: ProviderType): string {
  switch (providerType) {
    case "anthropic":
      return "Anthropic";
    case "openai":
      return "OpenAI";
    case "google":
      return "Google";
    case "openai-compatible":
      return "OpenAI Compatible";
  }
}

export function sourceModeLabel(source: ProviderSource): string {
  if (source.kind === "custom") {
    return "自定义接入";
  }

  return source.mode === "native" ? "官方接口" : "自定义中转";
}
