import type {
  ModelCapabilities,
  ModelCapabilitiesOverride,
  ModelEntry,
  ModelLimits,
  ModelLimitsOverride,
  ProviderSource,
  ProviderSourceDraft,
  SourceCredentials,
} from "@shared/contracts";
import {
  findKnownModelMetadata,
  getUnknownModelCapabilities,
  getUnknownModelLimits,
} from "@shared/provider-directory";
import {
  getProviderErrorLabel,
  type ProviderErrorCode,
} from "@shared/provider-errors";
import {
  deriveModelEntryName,
  isAutoGeneratedModelEntryName,
} from "@renderer/lib/provider-directory";

export type EditableEntry = {
  id: string;
  persistedId?: string;
  sourceId: string;
  name: string;
  modelId: string;
  enabled: boolean;
  builtin: boolean;
  capabilities: ModelCapabilitiesOverride;
  limits: ModelLimitsOverride;
  detectedCapabilities: ModelCapabilities;
  detectedLimits: ModelLimits;
  providerOptionsText: string;
};

export type SourceWorkspace = {
  sourceId: string;
  persistedSourceId?: string;
  kind: ProviderSource["kind"];
  sourceDraft: ProviderSourceDraft;
  hasStoredCredential: boolean;
  credentialMasked: string;
  apiKeyInput: string;
  entries: EditableEntry[];
  deletedEntryIds: string[];
  baseline: string;
};

export type LocalProviderPreset = {
  id: "ollama" | "lm-studio";
  label: string;
  sourceName: string;
  baseUrl: string;
  apiKey: string;
  model: {
    name: string;
    modelId: string;
  };
};

export const PROVIDER_TYPE_OPTIONS = [
  { value: "anthropic", label: "Anthropic" },
  { value: "openai", label: "OpenAI" },
  { value: "google", label: "Google" },
  { value: "openai-compatible", label: "OpenAI Compatible" },
] as const;

export const LOCAL_PROVIDER_PRESETS: LocalProviderPreset[] = [
  {
    id: "ollama",
    label: "Ollama",
    sourceName: "Ollama",
    baseUrl: "http://localhost:11434/v1",
    apiKey: "ollama",
    model: {
      name: "Ollama qwen2.5 7B",
      modelId: "qwen2.5:7b",
    },
  },
  {
    id: "lm-studio",
    label: "LM Studio",
    sourceName: "LM Studio",
    baseUrl: "http://localhost:1234/v1",
    apiKey: "lm-studio",
    model: {
      name: "LM Studio Local Model",
      modelId: "local-model",
    },
  },
];

const LOCAL_OPENAI_COMPAT_PROVIDER_OPTIONS = JSON.stringify(
  {
    compat: {
      supportsStore: false,
      supportsDeveloperRole: false,
      supportsReasoningEffort: false,
      maxTokensField: "max_tokens",
    },
  },
  null,
  2,
);

export const CAPABILITY_FIELDS = [
  { key: "vision", label: "视觉" },
  { key: "imageOutput", label: "图像输出" },
  { key: "toolCalling", label: "工具调用" },
  { key: "reasoning", label: "推理" },
  { key: "embedding", label: "向量 Embedding" },
] as const;

export function formatProviderError(
  error: string | undefined,
  errorCode: ProviderErrorCode | undefined,
  fallback: string,
): string {
  const message = error ?? fallback;
  return errorCode ? `${getProviderErrorLabel(errorCode)}：${message}` : message;
}

function normalizeCapabilityOverride(value: boolean | null): boolean | null {
  return typeof value === "boolean" ? value : null;
}

export function normalizeCapabilitiesOverride(
  capabilities: ModelCapabilitiesOverride,
): ModelCapabilitiesOverride {
  return {
    vision: normalizeCapabilityOverride(capabilities.vision),
    imageOutput: normalizeCapabilityOverride(capabilities.imageOutput),
    toolCalling: normalizeCapabilityOverride(capabilities.toolCalling),
    reasoning: normalizeCapabilityOverride(capabilities.reasoning),
    embedding: normalizeCapabilityOverride(capabilities.embedding),
  };
}

export function serializeWorkspace(workspace: SourceWorkspace): string {
  return JSON.stringify({
    sourceDraft: workspace.sourceDraft,
    apiKeyInput: workspace.apiKeyInput,
    deletedEntryIds: workspace.deletedEntryIds,
    entries: workspace.entries.map((entry) => ({
      id: entry.id,
      sourceId: entry.sourceId,
      name: entry.name,
      modelId: entry.modelId,
      enabled: entry.enabled,
      builtin: entry.builtin,
      capabilities: entry.capabilities,
      limits: entry.limits,
      providerOptionsText: entry.providerOptionsText,
    })),
  });
}

export function cloneEditableEntry(entry: EditableEntry): EditableEntry {
  return {
    ...entry,
    capabilities: { ...entry.capabilities },
    limits: { ...entry.limits },
    detectedCapabilities: { ...entry.detectedCapabilities },
    detectedLimits: { ...entry.detectedLimits },
  };
}

export function serializeEditableEntry(entry: EditableEntry): string {
  return JSON.stringify({
    id: entry.id,
    sourceId: entry.sourceId,
    name: entry.name,
    modelId: entry.modelId,
    enabled: entry.enabled,
    builtin: entry.builtin,
    capabilities: entry.capabilities,
    limits: entry.limits,
    providerOptionsText: entry.providerOptionsText,
  });
}

export function getDetectedMetadata(
  modelId: string,
  fallback?: {
    detectedCapabilities: ModelCapabilities;
    detectedLimits: ModelLimits;
  },
): Pick<EditableEntry, "detectedCapabilities" | "detectedLimits"> {
  const knownMetadata = findKnownModelMetadata(modelId);
  if (knownMetadata) {
    return {
      detectedCapabilities: knownMetadata.detectedCapabilities,
      detectedLimits: knownMetadata.detectedLimits,
    };
  }

  return {
    detectedCapabilities: fallback
      ? { ...fallback.detectedCapabilities }
      : getUnknownModelCapabilities(),
    detectedLimits: fallback
      ? { ...fallback.detectedLimits }
      : getUnknownModelLimits(),
  };
}

export function applyDetectedMetadata(
  entry: EditableEntry,
  modelId: string,
): EditableEntry {
  return {
    ...entry,
    modelId,
    ...getDetectedMetadata(modelId),
  };
}

export function getEntryDisplayName(entry: EditableEntry): string {
  if (entry.builtin) {
    return entry.name;
  }

  const manualName = entry.name.trim();
  return manualName || deriveModelEntryName(entry.modelId);
}

export function getEntryNameHint(entry: EditableEntry): string {
  if (entry.builtin) {
    return "内置模型名称";
  }

  return isAutoGeneratedModelEntryName(entry.name, entry.modelId)
    ? "将直接使用模型 ID 作为显示名称"
    : "当前使用自定义显示名称";
}

function resolveEditableCustomName(entry: ModelEntry): string {
  if (entry.builtin) {
    return entry.name;
  }

  if (isAutoGeneratedModelEntryName(entry.name, entry.modelId)) {
    return "";
  }

  return entry.name;
}

export function createEditableEntry(entry: ModelEntry): EditableEntry {
  const customName = resolveEditableCustomName(entry);
  const detectedMetadata = getDetectedMetadata(entry.modelId, {
    detectedCapabilities: entry.detectedCapabilities,
    detectedLimits: entry.detectedLimits,
  });

  return {
    id: entry.id,
    persistedId: entry.id,
    sourceId: entry.sourceId,
    name: customName,
    modelId: entry.modelId,
    enabled: entry.enabled,
    builtin: entry.builtin,
    capabilities: normalizeCapabilitiesOverride(entry.capabilities),
    limits: { ...entry.limits },
    detectedCapabilities: detectedMetadata.detectedCapabilities,
    detectedLimits: detectedMetadata.detectedLimits,
    providerOptionsText: entry.providerOptions
      ? JSON.stringify(entry.providerOptions, null, 2)
      : "",
  };
}

export function createWorkspace(
  source: ProviderSource,
  entries: ModelEntry[],
  credentials: SourceCredentials,
): SourceWorkspace {
  const workspace: SourceWorkspace = {
    sourceId: source.id,
    persistedSourceId: source.id,
    kind: source.kind,
    sourceDraft: {
      id: source.id,
      name: source.name,
      providerType: source.providerType,
      mode: source.mode,
      enabled: source.enabled,
      baseUrl: source.baseUrl ?? "",
    },
    hasStoredCredential: credentials.hasKey,
    credentialMasked: credentials.masked,
    apiKeyInput: "",
    entries: entries.map(createEditableEntry),
    deletedEntryIds: [],
    baseline: "",
  };
  workspace.baseline = serializeWorkspace(workspace);
  return workspace;
}

export function createDefaultCredentials(sourceId: string): SourceCredentials {
  return {
    sourceId,
    masked: "",
    hasKey: false,
  };
}

export function createWorkspaceMap(
  sources: ProviderSource[],
  entries: ModelEntry[],
  credentialsMap?: Map<string, SourceCredentials>,
): Record<string, SourceWorkspace> {
  const entriesBySourceId = new Map<string, ModelEntry[]>();
  for (const entry of entries) {
    const sourceEntries = entriesBySourceId.get(entry.sourceId);
    if (sourceEntries) {
      sourceEntries.push(entry);
    } else {
      entriesBySourceId.set(entry.sourceId, [entry]);
    }
  }

  return Object.fromEntries(
    sources.map((source) => [
      source.id,
      createWorkspace(
        source,
        entriesBySourceId.get(source.id) ?? [],
        credentialsMap?.get(source.id) ?? createDefaultCredentials(source.id),
      ),
    ]),
  );
}

export function compareSourceWorkspace(
  left: SourceWorkspace,
  right: SourceWorkspace,
): number {
  if (left.sourceDraft.enabled !== right.sourceDraft.enabled) {
    return left.sourceDraft.enabled ? -1 : 1;
  }

  if (left.kind !== right.kind) {
    return left.kind === "builtin" ? -1 : 1;
  }

  return (left.sourceDraft.name || "未命名提供商").localeCompare(
    right.sourceDraft.name || "未命名提供商",
    "zh-CN",
  );
}

function sortSourceWorkspaces(workspaces: SourceWorkspace[]): SourceWorkspace[] {
  return [...workspaces].sort(compareSourceWorkspace);
}

export function getDefaultSelectedSourceId(
  workspaces: Record<string, SourceWorkspace>,
): string | null {
  return sortSourceWorkspaces(Object.values(workspaces))[0]?.sourceId ?? null;
}

export function createNewCustomWorkspace(): SourceWorkspace {
  const workspace: SourceWorkspace = {
    sourceId: `draft-source:${crypto.randomUUID()}`,
    kind: "custom",
    sourceDraft: {
      name: "",
      providerType: "openai-compatible",
      mode: "custom",
      enabled: true,
      baseUrl: "",
    },
    hasStoredCredential: false,
    credentialMasked: "",
    apiKeyInput: "",
    entries: [],
    deletedEntryIds: [],
    baseline: "",
  };
  workspace.baseline = serializeWorkspace(workspace);
  return workspace;
}

export function createLocalProviderWorkspace(preset: LocalProviderPreset): SourceWorkspace {
  const sourceId = `draft-source:${preset.id}:${crypto.randomUUID()}`;
  const modelMetadata = getDetectedMetadata(preset.model.modelId);
  const workspace: SourceWorkspace = {
    sourceId,
    kind: "custom",
    sourceDraft: {
      name: preset.sourceName,
      providerType: "openai-compatible",
      enabled: true,
      mode: "custom",
      baseUrl: preset.baseUrl,
    },
    hasStoredCredential: false,
    credentialMasked: "",
    apiKeyInput: preset.apiKey,
    entries: [
      {
        id: `draft-entry:${crypto.randomUUID()}`,
        sourceId,
        name: preset.model.name,
        modelId: preset.model.modelId,
        enabled: true,
        builtin: false,
        capabilities: {
          vision: null,
          imageOutput: null,
          toolCalling: null,
          reasoning: null,
          embedding: null,
        },
        limits: {
          contextWindow: null,
          maxOutputTokens: null,
        },
        providerOptionsText: LOCAL_OPENAI_COMPAT_PROVIDER_OPTIONS,
        detectedCapabilities: modelMetadata.detectedCapabilities,
        detectedLimits: modelMetadata.detectedLimits,
      },
    ],
    deletedEntryIds: [],
    baseline: "",
  };
  return workspace;
}

export function parseOptionalNumber(value: string): number | null {
  const trimmed = value.trim();
  if (!trimmed) return null;
  const parsed = Number(trimmed);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null;
}

export function parseProviderOptions(text: string): Record<string, unknown> | null {
  const trimmed = text.trim();
  if (!trimmed) return null;
  const parsed = JSON.parse(trimmed) as unknown;
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("providerOptions 必须是 JSON 对象。");
  }
  return parsed as Record<string, unknown>;
}

export function resolveCapabilityChecked(
  entry: EditableEntry,
  key: keyof ModelCapabilitiesOverride,
): boolean {
  return (entry.capabilities[key] ?? entry.detectedCapabilities[key]) === true;
}

export function toCapabilityOverrideValue(
  detected: boolean | null,
  checked: boolean,
) {
  if (checked) {
    return detected === true ? null : true;
  }

  return detected === true ? false : null;
}

export function formatAutoLimit(value: number | null): string {
  return value ? value.toLocaleString("zh-CN") : "未知";
}
